### ISSUE TITLE
Feature request: also show XML code value for keybinds

### ISSUE THREAD

**Issue by DaftMav** [ghorsey/EdBindings#2]
This app would be super useful for people programming VoiceAttack commands for Elite if it could also show the XML entry for any given keybind (and quickly copy it to clipboard), because those are used with programming VoiceAttack in combination with [bindED](https://alternerdtive.github.io/bindED/). (I believe they are the 'code' values in your ActionMappings.json file). Perhaps optional since not everyone needs these values.

For example a voice command to lower landing gear; instead of telling VA to press a specific key like "press L", you can look up the XML entry for it which is 'LandingGearToggle'. With bindED in VoiceAttack that key will be a variable available as 'edLandingGearToggle'. This will make the VoiceAttack command work with any keybinds you have set up in-game and can be shared with other players without having to be edited to their own keybinds.

Finding the correct keybind XML entry is a bit annoying currently as you need to dig though the XML bindings file, and since this app makes the bindings easily searchable it would be perfect for this VoiceAttack/bindED use case.

**Comment by ghorsey** [comment]
@DaftMav  This looks super easy to add.  I have the data already.  I read through the BindED docs.  It seems like you just need to include the `ed` prefix to all of the element names from the *.binds file.  

I'll get a quick build done for this tonight.  I'll just add a column BindED Variable.

**Comment by DaftMav** [comment]
Yeah bindED adds the 'ed' prefix to its variables used in VoiceAttack. The time consuming part is usually finding which element name you're looking for, so a column with the BindED variable would be perfect! 👍

**Comment by ghorsey** [comment]
I just added the VoiceAttack/BindED Variable column: https://github.com/ghorsey/EdBindings/releases/latest
